### ISSUE TITLE
2. Operador del biodigestor

### ISSUE THREAD

**Issue by Houssay-grupo4** [Houssay-grupo4/Backend_Biodigestor#6]
-  Como operador del biodigestor, quiero poder iniciar y detener el proceso de digestión.
-  Como operador del biodigestor, quiero poder controlar la temperatura y el pH del biodigestor.
-  Como operador del biodigestor, quiero poder agregar materiales de alimentación y extraer el biogás.

**Comment by Alejandro-Santangelo** [comment]
Cerrando esta issue como "No planeado" debido a un error de interpretacion en su creacion

**Comment by Houssay-grupo4** [comment]
Cerrando esta issue como "No planeado" debido a un error de interpretacion en su creacion
